# Generated by Django 4.1.13 on 2025-05-02 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='票品名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('initial_stock', models.PositiveIntegerField(default=0, verbose_name='初始库存')),
            ],
            options={
                'verbose_name': '票品',
                'verbose_name_plural': '票品',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seckill_app.ticket', verbose_name='票品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'unique_together': {('user', 'ticket')},
            },
        ),
    ]
