# Generated by Django 4.1.13 on 2025-05-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seckill_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_time'], 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
    ]
